### ISSUE TITLE
Spelling wrong

### ISSUE THREAD

**Issue by ShubhamGupta2505** [yogendradevil/Agri-Tech#2]
![image](https://github.com/yogendradevil/Agri-Tech/assets/80637922/477a3bf9-c6a4-4b32-a16c-b491a086efb1)

And Readme is very poor please fix it.

**Comment by yogendradevil** [comment]
Thank you, Shubham
though I am still working on it,
I will change the readme file later.

**Comment by ShubhamGupta2505** [comment]
fuck you

**Comment by ShubhamGupta2505** [comment]
ok
